# Generated by Django 4.2.16 on 2024-11-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals_id', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('jinru_Date', models.CharField(max_length=32)),
                ('chuqu_Date', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('Species', models.CharField(max_length=32)),
                ('Family', models.CharField(max_length=32)),
                ('Name', models.CharField(max_length=32)),
            ],
        ),
    ]
