# Generated by Django 4.2.16 on 2025-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalsdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='jinru_Date',
            new_name='animal_Befinded_Date',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='Family',
            new_name='animal_Family',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='animals_id',
            new_name='animal_Id',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='location',
            new_name='animal_Location',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='Name',
            new_name='animal_Name',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='Species',
            new_name='animal_Species',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='chuqu_Date',
            new_name='animal_chuqu_Date',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='time',
        ),
        migrations.AddField(
            model_name='animals',
            name='animal_Pic',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
