# Generated by Django 5.2.9 on 2025-12-29 03:12

import animalsdata.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalsdata', '0002_rename_jinru_date_animals_animal_befinded_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('scientific_name', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=animalsdata.models._upload_animal_photo, validators=[animalsdata.models._validate_image_size])),
                ('discovered_at', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=32)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('audit_status', models.CharField(default='pending', max_length=16)),
                ('audit_opinion', models.TextField(blank=True)),
                ('audit_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_animals', to=settings.AUTH_USER_MODEL)),
                ('discoverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_animals', to=settings.AUTH_USER_MODEL)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animalsdata.park')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='animalsdata.animal')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='animalsdata.animalcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=animalsdata.models._upload_status_photo, validators=[animalsdata.models._validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='animalsdata.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
