# Generated by Django 5.2.9 on 2026-01-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalsdata', '0003_park_animal_animalcomment_animalstatusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
