# Generated by Django 5.2.9 on 2026-01-02 10:38

import animalsdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalsdata', '0004_animal_species_alter_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=animalsdata.models._upload_park_cover, validators=[animalsdata.models._validate_image_size]),
        ),
    ]
