# Generated by Django 3.2.21 on 2026-09-05 13:16

import animalsdata.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animalsdata', '0005_park_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalcomment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=animalsdata.models._upload_comment_photo, validators=[animalsdata.models._validate_image_size]),
        ),
        migrations.AddField(
            model_name='animalcomment',
            name='photo_audit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_comment_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalcomment',
            name='photo_audit_opinion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animalcomment',
            name='photo_audit_status',
            field=models.CharField(default='approved', max_length=16),
        ),
        migrations.AddField(
            model_name='animalcomment',
            name='photo_audit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
